"""Blank-tag probe batch for every remaining unmodeled predefined data type,
James 2026-08-27: "you need to generate all your missing predefined
datatypes. just make it as a controller tag with no logic." Follows his
earlier plan ("might have to get the remaining declared one tag at a time
for analysis. no need for multiple copies of each") -- one file, one
Controller-scoped tag, no rung logic, per type.

Source of the full type list: the real Rockwell "Pre-defined data types"
list James pasted directly (2026-08-27), cross-checked type-by-type against
this project's own memory_model.yaml (`predefined_structures` +
`predefined_array_structures` + CAM) to find what's still missing. Plain
atomic types (BOOL/SINT/INT/DINT/LINT/REAL/LREAL/UDINT/UINT/ULINT/USINT/
DT/LDT/TIME/TIME32/LTIME/STRING) are excluded -- those are fully solved,
not "predefined structures" in the sizing-gap sense. MODULE is excluded
separately -- it's not a normal user-declarable Tag DataType (module status
tags are generated by the I/O tree, not hand-created), so a bare
`<Tag DataType="MODULE">` would test something that doesn't reflect real
usage.

This is a DISCOVERY batch, not a sizing batch: nobody knows the real member
layout for most of these yet (only a name from Rockwell's own list), so the
Data body is an honest, non-fabricated placeholder -- an empty
`<Structure DataType="{type}"/>` -- rather than a guessed field list. When
these get run through Studio 5000 (import/conversion), the result itself is
the experiment: either it resolves cleanly and re-exports with the real
member layout (a definitive answer, better than anything guessable from
documentation), or it errors, which is equally real information (confirms
the type needs a different declaration shape, or isn't independently
declarable at all). 9 of these types already have real `Data Format="L5K"`
evidence sitting in samples/local/ (PID, MOVING_AVERAGE, PROP_INT, SELECT,
SERIAL_PORT_CONTROL, EMERGENCY_STOP, REDUNDANT_INPUT, REDUNDANT_OUTPUT,
LIGHT_CURTAIN) -- deliberately NOT used here; that's a separate, deeper
bit-level derivation task (same technique as FBD_BOOLEAN_AND/OR/NOT),
tracked in OPEN_QUESTIONS.md, not blocking this mechanical probe batch.

Run: python -m sample_gen.gen_predefined_probe
"""

from __future__ import annotations

from pathlib import Path

from sample_gen.manifest import append_manifest_row, write_sample_unmodeled
from sample_gen.wrapper import build_l5x

OUT_ROOT = Path(__file__).parent.parent.parent / "samples" / "generated" / "predefined"

# Full real Rockwell "Pre-defined data types" list (James, 2026-08-27 paste),
# minus plain atomics, minus what's already wired in memory_model.yaml
# (predefined_structures / predefined_array_structures / CAM), minus MODULE
# (not a normal declarable Tag DataType -- see docstring).
MISSING_TYPES = [
    "ALARM", "ALARM_ANALOG", "ALARM_DIGITAL", "ALARM_SET_CONTROL",
    "AUX_VALVE_CONTROL", "AXIS_CONSUMED", "AXIS_GENERIC", "AXIS_GENERIC_DRIVE",
    "AXIS_SERVO_DRIVE", "BUS_OBJ", "CAM_EXTENDED", "CAMSHAFT_MONITOR",
    "CAM_PROFILE_EXTENDED", "CB_CONTINUOUS_MODE", "CB_CRANKSHAFT_POS_MONITOR",
    "CB_INCH_MODE", "CB_SINGLE_STROKE_MODE", "CC", "CONFIGURABLE_ROUT",
    "CONNECTION_STATUS", "DATALOG_INSTRUCTION", "DCAF_INPUT", "DCA_INPUT",
    "DCI_MONITOR", "DCI_START", "DCI_STOP", "DCI_STOP_TEST",
    "DCI_STOP_TEST_LOCK", "DCI_STOP_TEST_MUTE", "DEADTIME", "DERIVATIVE",
    "DISCRETE_2STATE", "DISCRETE_3STATE", "DIVERSE_INPUT", "DOMINANT_RESET",
    "DOMINANT_SET", "DYNAMICS_DATA", "EIGHT_POS_MODE_SELECTOR",
    "EMERGENCY_STOP", "ENABLE_PENDANT", "ENERGY_BASE", "ENERGY_ELECTRICAL",
    "EXT_ROUTINE_CONTROL", "EXT_ROUTINE_PARAMETERS", "FBD_BIT_FIELD_DISTRIBUTE",
    "FBD_BOOLEAN_XOR", "FBD_COMPARE", "FBD_CONVERT", "FBD_COUNTER",
    "FBD_LIMIT", "FBD_LOGICAL", "FBD_MASKED_MOVE", "FBD_MASK_EQUAL",
    "FBD_MATH_ADVANCED", "FBD_TRUNCATE", "FILTER_HIGH_PASS", "FILTER_LOW_PASS",
    "FILTER_NOTCH", "FIVE_POS_MODE_SELECTOR", "FLIP_FLOP_D", "FLIP_FLOP_JK",
    "FUNCTION_GENERATOR", "HL_LIMIT", "HMIBC", "IMC", "INTEGRATOR",
    "LEAD_LAG", "LEAD_LAG_SEC_ORDER", "LIGHT_CURTAIN", "MAIN_VALVE_CONTROL",
    "MANUAL_VALVE_CONTROL", "MAXIMUM_CAPTURE", "MESSAGE", "MINIMUM_CAPTURE",
    "MMC", "MOVING_AVERAGE", "MOVING_STD_DEV", "MULTIPLEXER",
    "MUTING_FOUR_SENSOR_BIDIR", "MUTING_TWO_SENSOR_ASYM",
    "MUTING_TWO_SENSOR_SYM", "ODOMETER", "OPCUA_SERVER_ADDRESS", "OUTPUT_CAM",
    "OUTPUT_COMPENSATION", "PATH_DATA", "PHASE", "PHASE_INSTRUCTION", "PID",
    "PIDE_AUTOTUNE", "PID_ENHANCED", "POSITION_DATA", "POSITION_PROP",
    "PROP_INT", "P_ANALOG_FANOUT", "P_ANALOG_HART", "P_ANALOG_INPUT",
    "P_ANALOG_INPUT_DUAL", "P_ANALOG_INPUT_MULTI", "P_ANALOG_OUTPUT",
    "P_BOOLEAN_LOGIC", "P_COMMAND_SOURCE", "P_DEADBAND", "P_DISCRETE_4STATE",
    "P_DISCRETE_INPUT", "P_DISCRETE_MIX_PROOF", "P_DISCRETE_N_POSITION",
    "P_DISCRETE_OUTPUT", "P_DOSING", "P_HART_CODE_DESC_STATUS",
    "P_HIGH_LOW_SELECT", "P_INTERLOCK", "P_INTERLOCK_BANK_STATUS",
    "P_LEAD_LAG_STANDBY", "P_LEAD_LAG_STANDBY_MOTOR", "P_MOTOR_DISCRETE",
    "P_PERMISSIVE", "P_PID", "P_PRESS_TEMP_COMPENSATED", "P_RESTART_INHIBIT",
    "P_RUN_TIME", "P_STRAPPING_TABLE_ROW", "P_TANK_STRAPPING_TABLE",
    "P_VALVE_DISCRETE", "P_VALVE_STATISTICS", "P_VARIABLE_SPEED_DRIVE",
    "PULSE_MULTIPLIER", "RAC_CODE_DESCRIPTION", "RAC_EVENT",
    "RAC_ITF_DVC_PWRDISCRETE_CMD", "RAC_ITF_DVC_PWRDISCRETE_SET",
    "RAC_ITF_DVC_PWRDISCRETE_STS", "RAC_ITF_DVC_PWRMOTION_CMD",
    "RAC_ITF_DVC_PWRMOTION_INF", "RAC_ITF_DVC_PWRMOTION_SET",
    "RAC_ITF_DVC_PWRMOTION_STS", "RAC_ITF_DVC_PWRVELOCITY_CMD",
    "RAC_ITF_DVC_PWRVELOCITY_SET", "RAC_ITF_DVC_PWRVELOCITY_STS",
    "RAMP_SOAK", "REDUNDANT_INPUT", "REDUNDANT_OUTPUT",
    "REF_TO_AXIS_CIP_DRIVE", "REF_TO_AXIS_CONSUMED",
    "REF_TO_AXIS_GENERAL_DRIVE", "REF_TO_AXIS_SERVO",
    "REF_TO_AXIS_SERVO_DRIVE", "REF_TO_AXIS_VIRTUAL",
    "REF_TO_COORDINATE_SYSTEM", "SAFELY_LIMITED_POSITION",
    "SAFELY_LIMITED_SPEED", "SAFETY_FEEDBACK_INTERFACE", "SAFETY_MAT",
    "SAFE_BRAKE_CONTROL", "SAFE_DIRECTION", "SAFE_OPERATING_STOP",
    "SAFE_STOP_1", "SAFE_STOP_2", "SEC_ORDER_CONTROLLER", "SELECT",
    "SELECTABLE_NEGATE", "SELECTED_SUMMER", "SELECT_ENHANCED", "SEQUENCE",
    "SEQ_BOOL", "SEQ_DINT", "SEQ_INT", "SEQ_REAL", "SEQ_SINT", "SEQ_STEP",
    "SEQ_STRING", "SEQ_TRANSITION", "SERIAL_PORT_CONTROL", "SFC_STOP",
    "SIGNED_ODOMETER", "SPLIT_RANGE", "STRING_16", "STRING_32", "S_CURVE",
    "THRS_ENHANCED", "TIMER_T", "TOTALIZER", "TWO_HAND_RUN_STATION",
    "UP_DOWN_ACCUM",
]


def _probe_tag_xml(data_type: str) -> str:
    # Honest placeholder -- an empty Structure, not a guessed member list.
    # See module docstring for why: the whole point of this batch is to let
    # Studio 5000 itself resolve (or reject) each type, not to pre-guess it.
    return (
        f'      <Tag Name="Probe1" TagType="Base" DataType="{data_type}" '
        f'Constant="false" ExternalAccess="Read/Write">\n'
        f'        <Data Format="Decorated"><Structure DataType="{data_type}"/></Data>\n'
        f"      </Tag>"
    )


def _write(out_name: str, l5x: str, description: str) -> None:
    out_path = OUT_ROOT / f"{out_name}.L5X"
    write_sample_unmodeled(l5x, out_path)
    append_manifest_row(out_name, description, "predefined", out_path, 0)


def main() -> None:
    for data_type in MISSING_TYPES:
        slug = data_type.lower()
        tag = _probe_tag_xml(data_type)
        l5x = build_l5x(target_name=f"Probe{slug.title().replace('_', '')}", tags_xml=tag)
        _write(
            f"predefprobe_{slug}", l5x,
            f'Bare Controller tag "Probe1" DataType="{data_type}", no logic, empty placeholder '
            f"Structure body (real member layout unknown) -- discovery probe for Studio 5000 "
            f"import/conversion, James 2026-08-27 (\"generate all your missing predefined "
            f"datatypes... just make it as a controller tag with no logic\")",
        )
        print(f"Wrote predefprobe_{slug}.L5X")
    print(f"\nDone. {len(MISSING_TYPES)} files.")


if __name__ == "__main__":
    main()
